# Solving Sudoku Puzzles
## Assignment Preamble
Please ensure you carefully read all of the details and instructions on the assignment page, this section, and the rest of the notebook. If anything is unclear at any time please post on the forum or ask a tutor well in advance of the assignment deadline.

In addition to all of the instructions in the body of the assignment below, you must also follow the following technical instructions for all assignments in this unit. *Failure to do so may result in a grade of zero.*
* [At the bottom of the page](#Submission-Test) is some code which checks you meet the submission requirements. You **must** ensure that this runs correctly before submission.
* Do not modify or delete any of the cells that are marked as test cells, even if they appear to be empty.
* Do not duplicate any cells in the notebook – this can break the marking script. Instead, insert a new cell (e.g. from the menu) and copy across any contents as necessary.

Remember to save and backup your work regularly, and double-check you are submitting the correct version.

This notebook is the primary reference for your submission. You may write code in separate `.py` files but it must be clearly imported into the notebook so that it runs without needing to reference those files, and you must explain clearly what functionality is contained in those files (through comments, markdown cells, etc).

As always, **the work you submit for this assignment must be entirely your own.** Do not copy or work with other students. Do not copy answers that you find online. These assignments are designed to help improve your understanding first and foremost – the process of doing the assignment is part of *learning*. They are also used to assess your ability, and so you must uphold academic integrity. Submitting plagiarised work risks your entire place on your degree.

**The pass mark for this assignment is 40%.** We expect that students, on average, will be able to produce a submission which gets a mark between 50-70% within the normal workload allocation for the unit, but this will vary depending on individual backgrounds. Please ask for help if you are struggling.

## Getting Started
For this assignment, you will be writing an agent that can solve sudoku puzzles. You should be familiar with sudoku puzzles from the unit material. You are given a 9x9 grid with some fixed values. To solve the puzzle, the objective is to fill the empty cells of the grid such that the numbers 1 to 9 appear exactly once in each row, column, and 3x3 block of the grid. 

Below is a sample puzzle along with its solution. 

<img src="images/sudoku.png" style="width: 50%;"/>

For the this part of the assignment you will need to submit the implementation for an agent which can solve sudoku puzzles – this notebook:
 * You can use any algorithm you like, from the unit material or otherwise
 * Your code will be subject to automated testing, from which grades will be assigned based on whether it can solve sudokus of varying difficulty
 * To get a high grade on this assignment, the speed of your code will also be a factor – the quicker the better
 * There are some sample tests included below, make sure your code is compatible with the format of these tests

### Choice of Algorithm
The choice of algorithm to solve sudoku puzzles is up to you. We expect you will use search techniques from the unit, but you could make something up yourself, or do some independent research to find something else. You will need to evaluate and balance the trade-off between how well suited you think the algorithm is and how difficult it is to write, but there is some advice below.

I suggest you implement *constraint satisfaction* as it is described in the unit material. You can use the code you have previously been given as a guide. A good implementation of a backtracking depth-first search with constraint propagation should be sufficient to get a good grade in the automated tests (roughly 60-70%).

You could also write a successful agent that uses the other search techniques you have seen in the unit so far: basic search, heuristic search, or local search. You may find these easier to implement, though they may perform less well. 

To get a high grade on this assignment will require a particularly efficient implementation of constraint satisfaction, or something which goes beyond the material we have presented. *This is left unguided and is not factored into the unit workload estimates.*

If you choose to implement more than one algorithm, please feel free to include your code and write about it in part two (report), but only the code in this notebook will be used in the automated testing.

## Sample Sudoku Puzzles
To get started, the cell below will load in some sample sudoku puzzles for you so you can see the format. There are sudokus provided of multiple difficulties (easier sudokus typically start with more digits provided). The cell below only loads the easiest, but there is another test cell lower in the notebook which will run your code against all of the provided puzzles.

Each sudoku is a 9x9 NumPy array of integers, where zero represents an empty square. Each difficulty comes with 15 sudokus, so when you load the file, it is stored in a 15x9x9 array.

In [1]:
import numpy as np

# Load sudokus
sudoku = np.load("data/very_easy_puzzle.npy")
print("very_easy_puzzle.npy has been loaded into the variable sudoku")
print(f"sudoku.shape: {sudoku.shape}, sudoku[0].shape: {sudoku[0].shape}, sudoku.dtype: {sudoku.dtype}")

# Load solutions for demonstration
solutions = np.load("data/very_easy_solution.npy")
print()

# Print the first 9x9 sudoku...
print("First sudoku:")
print(sudoku[0], "\n")

# ...and its solution
print("Solution of first sudoku:")
print(solutions[0])

very_easy_puzzle.npy has been loaded into the variable sudoku
sudoku.shape: (15, 9, 9), sudoku[0].shape: (9, 9), sudoku.dtype: int8

First sudoku:
[[1 0 4 3 8 2 9 5 6]
 [2 0 5 4 6 7 1 3 8]
 [3 8 6 9 5 1 4 0 2]
 [4 6 1 5 2 3 8 9 7]
 [7 3 8 1 4 9 6 2 5]
 [9 5 2 8 7 6 3 1 4]
 [5 2 9 6 3 4 7 8 1]
 [6 0 7 2 9 8 5 4 3]
 [8 4 3 0 1 5 2 6 9]] 

Solution of first sudoku:
[[1 7 4 3 8 2 9 5 6]
 [2 9 5 4 6 7 1 3 8]
 [3 8 6 9 5 1 4 7 2]
 [4 6 1 5 2 3 8 9 7]
 [7 3 8 1 4 9 6 2 5]
 [9 5 2 8 7 6 3 1 4]
 [5 2 9 6 3 4 7 8 1]
 [6 1 7 2 9 8 5 4 3]
 [8 4 3 7 1 5 2 6 9]]


## Part One
You should write all of your code for solving sudokus below this cell.

You must include a function called `sudoku_solver(sudoku)` which takes one sudoku puzzle (a 9x9 NumPy array) as input, and returns the solved sudoku as another 9x9 NumPy array. This is the function which will be tested. 

In [2]:
import numpy as np
import itertools
from collections import defaultdict


class SudokuSolver:
    def __init__(self):
        self.lcv_cache = {}
        self.all_units = self.get_sudoku_units()

    def work_out_lcv(self, sudoku, candidates, row, col, num):
        # Check if the result is cached
        if (row, col, num) in self.lcv_cache:
            return self.lcv_cache[(row, col, num)]

        constraint_count = 0
        # Check same row and column
        for i in range(9):
            if i != col and num in candidates[row][i]:
                constraint_count += 1
            if i != row and num in candidates[i][col]:
                constraint_count += 1

        # Check same box
        box_row_start, box_col_start = 3 * (row // 3), 3 * (col // 3)
        for i in range(box_row_start, box_row_start + 3):
            for j in range(box_col_start, box_col_start + 3):
                if (i != row or j != col) and num in candidates[i][j]:
                    constraint_count += 1

        # Cache the result
        self.lcv_cache[(row, col, num)] = constraint_count
        return constraint_count

    def clear_cache(self):
        self.lcv_cache.clear()

    def get_sudoku_units(self):
        units = []

        # Rows
        for i in range(9):
            units.append([(i, j) for j in range(9)])

        # Columns
        for j in range(9):
            units.append([(i, j) for i in range(9)])

        # 3x3 Boxes
        for box_row in range(0, 9, 3):
            for box_col in range(0, 9, 3):
                units.append([(box_row + i, box_col + j) for i in range(3) for j in range(3)])

        return units


lcv_solver = SudokuSolver()


def valid_move_check(sudoku, row, col, num):
    box_row = row - row % 3
    box_col = col - col % 3
    if num in sudoku[row] or num in sudoku[:, col] or num in sudoku[box_row:box_row + 3, box_col:box_col + 3].flatten():
        return False
    return True


def valid_puzzle_check(sudoku):
    """
    Validates if the given sudoku puzzle is correct according to Sudoku rules.

    This function checks every row, column, and 3x3 box to ensure that there are no duplicate
    numbers. Only non-zero elements are considered since zeros represent empty cells.

    """
    for i in range(9):
        row = sudoku[i, :]
        col = sudoku[:, i]
        box = sudoku[3 * (i // 3):3 * (i // 3) + 3, 3 * (i % 3):3 * (i % 3) + 3].flatten()

        if np.unique(row[row > 0]).size != row[row > 0].size:
            return False
        if np.unique(col[col > 0]).size != col[col > 0].size:
            return False
        if np.unique(box[box > 0]).size != box[box > 0].size:
            return False
    return True


def find_initial_candidates(sudoku):
    """
    Initialises the candidates for each cell in the Sudoku puzzle.

    Each cell gets a set of possible numbers (1-9) if it's empty (denoted by 0), or an empty set if it already
    has a number. This is used to track the allowed values for each cell as the puzzle is being solved.

    """
    candidates = [[set(range(1, 10)) if sudoku[i][j] == 0 else set() for j in range(9)] for i in range(9)]
    for i in range(9):
        for j in range(9):
            if sudoku[i][j] != 0:
                # Update the candidates immediately based on the initial numbers on the board.
                update_candidates(candidates, i, j, sudoku[i][j], None)
    return candidates


def update_candidates(candidates, row, col, num, history=None):
    """
    Updates the candidates for cells affected by placing a number in the given cell.

    This function removes the number from the candidates of all cells in the same row, column,
    and 3x3 box. It keeps track of changes for possible backtracking.

    """
    changes = []  # To keep track of the changes for backtracking.

    # Update candidates in the same row and column.
    for i in range(9):
        if num in candidates[row][i] and i != col:
            changes.append(((row, i), candidates[row][i].copy()))
            candidates[row][i].discard(num)

        if num in candidates[i][col] and i != row:
            changes.append(((i, col), candidates[i][col].copy()))
            candidates[i][col].discard(num)

    # Update candidates in the same 3x3 box.
    box_row_start, box_col_start = 3 * (row // 3), 3 * (col // 3)
    for i in range(box_row_start, box_row_start + 3):
        for j in range(box_col_start, box_col_start + 3):
            if num in candidates[i][j] and (i, j) != (row, col):
                changes.append(((i, j), candidates[i][j].copy()))
                candidates[i][j].discard(num)

    # Record changes if history is being kept.
    if history is not None:
        history.append(changes)


def reset_candidates(candidates, history):
    """
    Resets the candidates for cells to a previous state.

    This function is used for backtracking, where it reverts the candidates to their state before
    the last attempted number placement.

    """
    last_changes = history.pop()  # Get the last set of changes to undo.
    for cell, prev_candidates in last_changes:
        candidates[cell[0]][cell[1]] = prev_candidates


def discard_row_outside_box(sudoku, candidates, row, box_col, num):
    changed = False
    for col in range(9):
        if box_col <= col < box_col + 3:
            continue
        if num in candidates[row][col]:
            candidates[row][col].discard(num)
            changed = True
    return changed


def discard_column_outside_box(sudoku, candidates, col, box_row, num):
    changed = False
    for row in range(9):
        if box_row <= row < box_row + 3:
            continue
        if num in candidates[row][col]:
            candidates[row][col].discard(num)
            changed = True
    return changed


def pointing_pairs(sudoku, candidates):
    made_progress = False

    for box_row in range(0, 9, 3):
        for box_col in range(0, 9, 3):
            for num in range(1, 10):
                cells = [(r, c) for r in range(box_row, box_row + 3) for c in range(box_col, box_col + 3) if
                         num in candidates[r][c]]
                if not cells:
                    continue

                rows, cols = zip(*cells)
                unique_rows, unique_cols = set(rows), set(cols)

                if len(unique_rows) == 1:
                    made_progress |= discard_row_outside_box(sudoku, candidates, unique_rows.pop(), box_col, num)

                if len(unique_cols) == 1:
                    made_progress |= discard_column_outside_box(sudoku, candidates, unique_cols.pop(), box_row, num)

    return made_progress


def naked_pairs(candidates):
    made_progress = False

    for unit in lcv_solver.all_units:
        # Check each combination of two cells within the unit
        for cell1, cell2 in itertools.combinations(unit, 2):
            if candidates[cell1[0]][cell1[1]] == candidates[cell2[0]][cell2[1]] and len(
                    candidates[cell1[0]][cell1[1]]) == 2:
                # Found a naked pair
                for cell in unit:
                    if cell != cell1 and cell != cell2:
                        # Remove these candidates from other cells in the unit
                        old_candidates = candidates[cell[0]][cell[1]].copy()
                        candidates[cell[0]][cell[1]] -= candidates[cell1[0]][cell1[1]]
                        if old_candidates != candidates[cell[0]][cell[1]]:
                            made_progress = True

    return made_progress


def hidden_pairs(candidates):
    made_progress = False

    for unit in lcv_solver.all_units:
        # Track the positions of each candidate number
        candidate_positions = defaultdict(list)
        for cell in unit:
            row, col = cell
            for num in candidates[row][col]:
                candidate_positions[num].append(cell)

        # Look for hidden pairs among the candidates
        for nums in itertools.combinations(range(1, 10), 2):
            common_cells = set(candidate_positions[nums[0]]) & set(candidate_positions[nums[1]])
            if len(common_cells) == 2:
                # Potential hidden pair found
                # Check if these are the only two cells where both nums appear
                if all(len(candidate_positions[num]) == 2 for num in nums):
                    for cell in common_cells:
                        row, col = cell
                        if candidates[row][col] != set(nums):
                            candidates[row][col] = set(nums)
                            made_progress = True

    return made_progress


def naked_singles(sudoku, candidates):
    made_progress = False
    single_candidate_cells = [(i, j) for i in range(9) for j in range(9) if len(candidates[i][j]) == 1]

    while single_candidate_cells:
        row, col = single_candidate_cells.pop()
        if sudoku[row][col] == 0 and len(candidates[row][col]) == 1:
            value = candidates[row][col].pop()
            sudoku[row][col] = value
            update_candidates_and_track_changes(candidates, row, col, value, single_candidate_cells)
            made_progress = True

    return made_progress


def update_candidates_and_track_changes(candidates, row, col, num, single_candidate_cells):
    """
    Updates the candidates for each cell after a number placement and tracks cells that
    become naked singles as a result.

    """
    # Update row candidates and add single candidates to tracking list
    for i in range(9):
        if i != col and num in candidates[row][i]:
            candidates[row][i].discard(num)
            if len(candidates[row][i]) == 1:
                single_candidate_cells.append((row, i))

    # Update column candidates and add single candidates to tracking list
    for i in range(9):
        if i != row and num in candidates[i][col]:
            candidates[i][col].discard(num)
            if len(candidates[i][col]) == 1:
                single_candidate_cells.append((i, col))

    # Update box candidates and add single candidates to tracking list
    box_row_start, box_col_start = 3 * (row // 3), 3 * (col // 3)
    for i in range(box_row_start, box_row_start + 3):
        for j in range(box_col_start, box_col_start + 3):
            if (i, j) != (row, col) and num in candidates[i][j]:
                candidates[i][j].discard(num)
                if len(candidates[i][j]) == 1:
                    single_candidate_cells.append((i, j))


def hidden_singles(sudoku, candidates):
    """
    Applies the hidden singles technique to the puzzle.

    This technique finds cells where a candidate number is the only possibility
    within a unit (row, column, or box) and fills in the number.

    """
    made_progress = False
    for unit in lcv_solver.all_units:
        for num in range(1, 10):
            cells = [cell for cell in unit if num in candidates[cell[0]][cell[1]]]
            if len(cells) == 1:
                row, col = cells[0]
                sudoku[row][col] = num
                candidates[row][col].clear()
                update_candidates(candidates, row, col, num)
                made_progress = True
    return made_progress


def sudoku_solver(sudoku):
    """
    Solves a Sudoku puzzle using constraint propagation and backtracking search.

    """
    candidates = find_initial_candidates(sudoku)
    history = []
    if not valid_puzzle_check(sudoku):
        return np.full((9, 9), -1)

    sudoku = initial_constraint_propagation(sudoku, candidates)
    # If puzzle is still not solved, use DFS backtracking with MRV
    if not check_is_sudoku_solved(sudoku):
        sudoku = finish_sudoku(sudoku, candidates, history)
    return sudoku


def initial_constraint_propagation(sudoku, candidates):
    # Apply naked and hidden singles first
    while True:
        made_progress = False

        made_progress = naked_singles(sudoku, candidates)
        made_progress = hidden_singles(sudoku, candidates)

        naked_pairs(candidates)

        if pointing_pairs(sudoku, candidates):
            made_progress = True

        hidden_pairs(candidates)

        if not made_progress:
            break
    return sudoku


def check_is_sudoku_solved(sudoku):
    """
    Checks if a Sudoku puzzle is solved.

    """
    return all(sudoku[i][j] != 0 for i in range(9) for j in range(9))


def find_best_cell_mrv(sudoku, candidates):
    """
    Finds the next empty cell with the minimum remaining possible values (MRV heuristic).

    """
    min_remaining_values = float('inf')
    selected_cell = None

    # Loop through each cell to find the one with the fewest candidates
    for i in range(9):
        for j in range(9):
            if sudoku[i][j] == 0:  # If the cell is empty
                num_candidates = len(candidates[i][j])
                if num_candidates < min_remaining_values:
                    min_remaining_values = num_candidates
                    selected_cell = (i, j)

    return selected_cell


def finish_sudoku(sudoku, candidates, history):
    """
    Solves the Sudoku puzzle using backtracking search with MRV and LCV heuristics.

    """
    # Find the next cell to fill based on the MRV heuristic
    mrv_cell = find_best_cell_mrv(sudoku, candidates)
    if mrv_cell is None:  # If there's no empty cell left, the puzzle is solved
        return np.array(sudoku) if check_is_sudoku_solved(sudoku) else np.full((9, 9), -1)

    row, col = mrv_cell
    # Sort candidates based on the LCV heuristic
    sorted_candidates = sorted(
        candidates[row][col],
        key=lambda num: lcv_solver.work_out_lcv(sudoku, candidates, row, col, num)
    )

    for num in sorted_candidates:
        # Try placing each candidate and use recursion.
        if valid_move_check(sudoku, row, col, num):
            sudoku[row][col] = num
            update_candidates(candidates, row, col, num, history)
            result = finish_sudoku(sudoku, candidates, history)
            if result is not None and not np.array_equal(result, np.full((9, 9), -1)):
                return result  # If a valid solution is found, return it

            # If the choice leads to no solution, backtrack
            sudoku[row][col] = 0
            reset_candidates(candidates, history)

    # If no candidates work, return invalid
    return np.full((9, 9), -1)





All of your code must go above this cell. You may add additional cells into the notebook if you wish, but do not duplicate or copy/paste cells as this can interfere with the grading script.

### Testing Details
There are four difficulties of sudoku provided: very easy, easy, medium, and hard. There are 15 sample sudokus in each category, with solutions as well. Difficulty was determined using reference solvers, but your code may vary; it is conceivable that your code will find some sudokus much easier or harder within a given category, or even between categories.

*All categories that are easy and above will contain* ***invalid initial states***, that is, sudoku puzzles with no solution. In this case, your function should return a 9x9 NumPy array whose values are all equal to -1.

When we test your code, we will firstly test it on the *same* very easy puzzles that you have been given. Then we will test it on additional *hidden* sudokus from each difficulty in turn, easy and up. Grades are awarded based on whether your code can solve the puzzles. For high grades on the hard puzzles, execution time will also be a factor. 

All puzzles must take under 30 seconds each on the test machine to count as successful, but you should be aiming for an average of under a second per puzzle. Hardware varies, but all tests will take place on the same modern desktop machine. Our ‘standard constraint satisfaction’ implementation takes about 0.001 seconds per puzzle for the very easy category, but struggles to solve some of the hard puzzles within the time limit.

***The hard sudokus are labelled as hard for a reason.*** We expect most submissions will not be able to solve them in a reasonable length of time. Use the stop button (■) on the toolbar if you need to terminate your code because it is taking too long.

The best way to improve the performance of your code is through a detailed understanding and smart choice of AI algorithms. This assignment is ***not*** meant to test your ability to write multi-threaded code or any other kind of high-performance code optimisations. 

#### Test Cell
The following code will run your solution over the provided sudoku puzzles. To enable it, set the constant `SKIP_TESTS` to `False`. If you fail any tests of one difficulty, the code will stop, but you can modify this behaviour if you like.

**IMPORTANT**: you must set `SKIP_TESTS` back to `True` before submitting this file!

In [3]:
SKIP_TESTS = True
if not SKIP_TESTS:
    import time
    import numpy as np
    __SCORES = {}
    difficulties = ['very_easy', 'easy', 'medium', 'hard']

    for difficulty in difficulties:
        print(f"Testing {difficulty} sudokus")
        
        sudokus = np.load(f"data/{difficulty}_puzzle.npy")
        solutions = np.load(f"data/{difficulty}_solution.npy")
        
        count = 0
        for i in range(len(sudokus)):
            sudoku = sudokus[i].copy()
            print(f"This is {difficulty} sudoku number", i)
            print(sudoku)
            
            start_time = time.process_time()
            your_solution = sudoku_solver(sudoku)
            end_time = time.process_time()
            
            if not isinstance(your_solution, np.ndarray):
                print("\033[91m[ERROR] Your sudoku_solver function returned a variable that has the incorrect type. If you submit this it will likely fail the auto-marking procedure result in a mark of 0 as it is expecting the function to return a numpy array with a shape (9,9).\n\t\033[94mYour function returns a {} object when {} was expected.\n\x1b[m".format(type(your_solution), np.ndarray))
            elif not np.all(your_solution.shape == (9, 9)):
                print("\033[91m[ERROR] Your sudoku_solver function returned an array that has the incorrect shape.  If you submit this it will likely fail the auto-marking procedure result in a mark of 0 as it is expecting the function to return a numpy array with a shape (9,9).\n\t\033[94mYour function returns an array with shape {} when {} was expected.\n\x1b[m".format(your_solution.shape, (9, 9)))
            
            print(f"This is your solution for {difficulty} sudoku number", i)
            print(your_solution)
            
            print("Is your solution correct?")
            if np.array_equal(your_solution, solutions[i]):
                print("Yes! Correct solution.")
                count += 1
            else:
                print("No, the correct solution is:")
                print(solutions[i])
            
            print("This sudoku took {} seconds to solve.\n".format(end_time-start_time))

        print(f"{count}/{len(sudokus)} {difficulty} sudokus correct")
        __SCORES[difficulty] = {
            'correct': count,
            'total': len(sudokus)
        }

## Submission Test
The following cell tests if your notebook is ready for submission. **You must not skip this step!**

Restart the kernel and run the entire notebook (Kernel → Restart & Run All). Now look at the output of the cell below. 

*If there is no output, then your submission is not ready.* Either your code is still running (did you forget to skip tests?) or it caused an error.

As previously mentioned, failing to follow these instructions can result in a grade of zero.

In [4]:
import sys
import pathlib

fail = False;

success = '\033[1;32m[✓]\033[0m'
issue = '\033[1;33m[!]'
error = '\033[1;31m\t✗'
indent_success = '\033[1;32m\t✓'

#######
##
## Skip Tests check.
##
## Test to ensure the SKIP_TESTS variable is set to True to prevent it slowing down the automarker.
##
#######

if not SKIP_TESTS:
    fail = True;
    print("{} \'SKIP_TESTS\' is incorrectly set to False.\033[0m".format(issue))
    print("{} You must set the SKIP_TESTS constant to True in the cell above.\033[0m".format(error))
else:
    print('{} \'SKIP_TESTS\' is set to true.\033[0m'.format(success))

#######
##
## Report File Check.
##
## Test that checks there is a report pdf file found in the same folder as the notebook. This is required by the coursework specification.
##
#######

p1 = pathlib.Path('./report.pdf')
p2 = pathlib.Path('./Report.pdf')
if not (p1.is_file() or p2.is_file()):
    fail = True;
    print("{} Report PDF not found.\033[0m".format(issue))
    print("{} You must include a separate file called report.pdf in your submission.\033[0m".format(error))
else:
    print('{} Report PDF found.\033[0m'.format(success))

#######
##
## File Name check.
##
## Test to ensure file has the correct name. This is important for the marking system to correctly process the submission.
##
#######
    
p3 = pathlib.Path('./sudoku.ipynb')
if not p3.is_file():
    fail = True
    print("{} The notebook name is incorrect.\033[0m".format(issue))
    print("{} This notebook file must be named sudoku.ipynb\033[0m".format(error))
else:
    print('{} The notebook name is correct.\033[0m'.format(success))

#######
##
## Create classifier function check.
##
## Test that checks the create_classifier function exists. The function should train the classifier and return it so that it can be evaluated by the marking system.
##
#######

if "sudoku_solver" not in dir():
    fail = True;
    print("{} The sudoku_solver function has not been defined.\033[0m".format(issue))
    print("{} Your code must include a sudoku_solver function as described in the coursework specification.\033[0m".format(error))
    print("{} If you believe you have, \'restart & run-all\' to clear this error.\033[0m".format(error))
else:
    print('{} The sudoku_solver function has been defined.\033[0m'.format(success))



try:
    _sudoku = np.load("data/very_easy_puzzle.npy")[0]
    _solution = np.load("data/very_easy_solution.npy")[0]

    if not np.array_equal(sudoku_solver(_sudoku), _solution):
        print("{} Your sudoku_solver function does not correctly solve the first sudoku.\033[0m".format(issue))
        print()
        print("{} Your assignment is unlikely to get any marks from the autograder. While we will\033[0m".format(error))
        print("{} try to check it manually to assign some partial credit, we encourage you to ask\033[0m".format(error))
        print("{} for help on the forum or directly to a tutor.\033[0m".format(error))
        print()
        print("{} Please use the report file to explain your code anyway.\033[0m".format(error))
    else:
        print("{} Your sudoku_solver function correctly solves the first sudoku.\033[0m".format(success))
        if "__SCORES" in dir():
#             print("{} Test set summary - Not Found.\033[0m".format(issue))
#             print("{} Test set summary could not be found. This is automatically generated when the \033[0m".format(error))
#             print("{} above test cell is run. If you would like to see the summary please run the above cell.\033[0m".format(error))
#             print("{} You do not need this for submission, it is only for your convenience.\033[0m".format(error))
#         else:
            correct = 0
            total = 0
            for key, value in __SCORES.items():
                correct += value['correct']
                total += value['total']
                
            print("{} Test set summary - {}/{} Correct.\033[0m".format(issue, correct, total))
            if total != correct:
                
                for key, value in __SCORES.items():
                    if value['correct'] == value['total']:
                        print("{} {}/{} of {} sudokus correct.\033[0m".format(indent_success, value['correct'], value['total'], key))
                    else:
                        print("{} {}/{} of {} sudokus correct.\033[0m".format(error, value['correct'], value['total'], key))
            
except Exception as e:
    fail = True
    print("{} Error running test set.\033[0m".format(issue))
    print("{} Your code produced the following error. This error will result in a zero from the automarker, please fix.\033[0m".format(error))
    print(e)

    

#######
##
## Final Summary
##
## Prints the final results of the submission tests.
##
#######

if fail:
    sys.stderr.write("Your submission is not ready! Please read and follow the instructions above.")
else:
    print("\033[1m\n\n")
    print("╔═══════════════════════════════════════════════════════════════╗")
    print("║                        Congratulations!                       ║")
    print("║                                                               ║")
    print("║            Your work meets all the required criteria          ║")
    print("║                   and is ready for submission.                ║")
    print("╚═══════════════════════════════════════════════════════════════╝")
    print("\033[0m")
    

[✓] 'SKIP_TESTS' is set to true.
[✓] Report PDF found.
[✓] The notebook name is correct.
[✓] The sudoku_solver function has been defined.
[✓] Your sudoku_solver function correctly solves the first sudoku.



╔═══════════════════════════════════════════════════════════════╗
║                        Congratulations!                       ║
║                                                               ║
║            Your work meets all the required criteria          ║
║                   and is ready for submission.                ║
╚═══════════════════════════════════════════════════════════════╝



In [5]:
# This is a TEST CELL. Do not delete or change.